version: "3.3"

services:
  ucf-poll-mysql:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ucfpoll
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
  ucf-poll-redis:
    image: redis:6
    volumes:
      - redis_data:/data
    restart: always
    ports:
      - 6379:6379

volumes:
  db_data: {}
  redis_data: {}
